version: '3.8'

services:
  app:
    image: locnguyen04/springbootapp-linux:2.1
    container_name: spring_boot_app
    ports:
      - "8080:8080"  # Map port của ứng dụng backend
    depends_on:
      - mysql

  mysql:
    image: locnguyen04/mysql-custom:2.0  # Image MySQL tùy chỉnh
    container_name: mysql_db
    ports:
      - "3307:3306"  # Map port của MySQL ra bên ngoài
    environment:
      MYSQL_ROOT_PASSWORD: 12345abc
      MYSQL_DATABASE: flightManagement
    volumes:
      - mysql-data:/var/lib/mysql  # Dữ liệu của MySQL

volumes:
  mysql-data:  # Volume lưu trữ dữ liệu MySQL